version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/app/static
    working_dir: /code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  lint:
    build: .
    command: flake8 .
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - PYTHONUNBUFFERED=1

  format:
    build: .
    command: sh -c "isort . && black ."
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - PYTHONUNBUFFERED=1

  test:
    build: .
    command: pytest
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=todolist.settings
volumes:
  static_volume:
